name: CI
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  build:
    uses: oapi-codegen/actions/.github/workflows/ci.yml@cdf6a353c2e582e96fcf472065e9673935ef0dd2 # v0.9.1
    with:
      lint_versions: '["1.26"]'
