name: CI
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  build:
    uses: oapi-codegen/actions/.github/workflows/ci.yml@f7f6944c57fdf23fc920076e41fd1dc6604eaad5 # v0.7.0
    with:
      lint_versions: '["1.25"]'
