name: Ensure generated files are up-to-date
on: [ push, pull_request ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # perform matrix testing to give us an earlier insight into issues with different versions of supported major versions of Go
      matrix:
        version:
        - "1.20"
        - "1.21"
        - "1.22"
    steps:
      - name: Check out source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ${{ matrix.version }}

      - name: Run `make generate`
        run: make generate

      - name: Check for no untracked files
        run: git status && git diff-index --quiet HEAD --
